### ISSUE TITLE
Dynamic generation of seed block

### ISSUE THREAD

**Issue by JimCircadian** [icenet-ai/icenet-pipeline#14]
The seed block in the ensembler templates is not portable, in that it needs to be the same between training and prediction, as well as shareable with those who link to pipelines to pick up models. 

This requires a bit of thought, but would be best solved sooner than later (the commands need to be model aware, which `run_prediction.sh` already kind of is...

@EllieBowler @ots22 you were both made aware of this so tagging you FYI

**Comment by JimCircadian** [comment]
Both `train.tmpl.yaml` and `predict.tmpl.yaml` need to have these dynamically generated seed blocks which determine the number of runs. Technically, we don't need the seed any more either (there could be complications with removing it though as the output networks contain the seed number, so that's not trivial (yet) to remove)...

...this is a really good issue to sort out. Should definitely be provided by ENVS rather than the CLI to the scripts.

**Comment by JimCircadian** [comment]
This looks good @bnubald. I'd not worry too much about the error checking, which is not something I'd normally advise, if we're taking from the ENVS the CLI will act as an override. 

I'd think about removing the default seed block and perhaps keeping it simple: just include a SEED element in the templates that can be exchanged using `sed`.

**Comment by bnubald** [comment]
Yes, the seed block was replaced with a default variable in the script that mimics the current output for backwards compatibility:

```
ENSEMBLE_SEEDS_DEFAULT=42,46,45,17,24,84,83,16,5,3
```

Then the `SEEDS` is replaced in the yaml with one of the 3 options mentioned above using `sed`.

```
  batches:
    - name:       NAME
      basedir:    ./ensemble/NAME                          
      pre_batch:  []              
      pre_run:    []                                          
      runs:
        - seed:   SEEDS                                 
      post_run:   []
```

Completed above for train.tmpl.yaml, after some more testing (CLI, ENVS and arg definitions working so far). Need to do same for predict.tmpl.yaml, will submit PR after doing so.
