### ISSUE TITLE
Remove pinning, and cuda install.

### ISSUE THREAD

**Issue by bnubald** [icenet-ai/icenet-pipeline#28]
Separate install of cudatoolkit, cudnn not required anymore, instead tensorflow [docs](https://www.tensorflow.org/install/pip) recommends:

`pip install tensorflow[and-cuda]`

Without it, will result in having to deal with package dependency issues when trying to install `icenet` library.

**Comment by JimCircadian** [comment]
@bnubald did I see a comment updating Python to 3.11? We shouldn't ideally be going too far forward, I tend to make sure I don't beyond 3.8 for various reasons

**Comment by bnubald** [comment]
See issue #30 that reverts this change to keep python 3.8.
